# -*- coding: utf-8 -*-
"""twitterinclass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REuDlADU1Hs_TQy6_5fjjl_28JfwMMeD
"""



import pandas as pd

tweets = pd.read_csv('https://raw.githubusercontent.com/AsmiBasnet/ab-tweets/refs/heads/main/Tweets.csv')

tweets.head()

sentiment_counts = tweets['airline_sentiment'].value_counts()

sentiment_counts.head()

import seaborn as sns
import matplotlib.pyplot as plt

sns.barplot(hue=sentiment_counts.index, y=sentiment_counts.values, palette='coolwarm')
plt.title('Airline Sentiment Count', fontsize=16)
plt.xlabel('Sentiment', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.show()